name: facelit-embedding-service

services:
  embedding-service:
    build: .
    env_file:
      - .env
    environment:
      PRELOAD_MODEL: "true"
    ports:
      - "${SERVICE_PORT:-8090}:8090"
    volumes:
      - insightface-models:/root/.insightface
    networks:
      - facelit-db-network

volumes:
  insightface-models:

networks:
  facelit-db-network:
    external: true
    name: facelit-docker-compose_default
